### PR TITLE
implement libmaxminddb support as an alternative to geoip

### PR DESCRIPTION
**Pull request by msehnout**
Described in issue #15.

@mruprich Could you please take a look at this PR if I am using the maxmind API correctly?

### CODE REVIEW

**Comment by nmav** [comment]
It seems that the maxmind code gets compiled even when not enabled. You may want to check the failures on travis. Some things after a quick glimpse to the code:
 * A test case is needed on travis for maxmind compilation
 * The database seems to be loaded from a hard-coded location. Doesn't the maxmind API give a way to get the distribution default location?
 * The linking seems to be done statically against maxmind. That's ok in general, but for a linux distribution I guess that's too much to pull maxmind because of ipcalc. If it is intended to be enabled in distros like fedora dynamic loading should be used.

**Comment by msehnout** [comment]
I fixed the Travis compilation. Regarding the hard-coded location, there is, unfortunately, no such function as `setup_dbfilename` from the legacy API. But it was guessing the name anyway so I decided to use macros instead and each package maintainer can choose whatever location they like. Regarding the dynamic linking, it is loaded dynamically when the OS is loading the process into memory. It seems to me as an unnecessary complication to do it by hand during runtime, when the operating system can do it for me.
```
$ ldd ./ipcalc 
	linux-vdso.so.1 (0x00007ffd6b3a4000)
	libmaxminddb.so.0 => /lib64/libmaxminddb.so.0 (0x00007fc8d4b38000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fc8d4779000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc8d4d3e000)
```

**Comment by nmav** [comment]
I know that the dynamic linker brings the libraries to address space automatically :) The reason the `dlopen()` happens with the geoip code is so that ipcalc doesn't need to have maxmind installed to function. If you remove maxmind from the system that you run ldd at you'll see that ipcalc would not be able to do any action. If you use dlopen as the current code does ipcalc will be functional even if maxmind is not there. That's especially important in minimal container or system installations.

**Comment by nmav** [comment]
Moved repo to https://gitlab.com/ipcalc/ipcalc

**Pull request closed without merging**
